language: android
sudo: required
jdk:
    - oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-24.0.3
        - android-24
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - extra-google-google_play_services

script:
    - ./gradlew build
deploy:
    provider: releases
    api_key:
        secure:afa7ab9fd5fdf2a3909938fcf069428d4b777ecb
    file: app/build/outputs/apk/app-release.apk
    skip_cleanup: true
    on:
        tags: true
