language: android
android:
    components:
        - build-tools-22.0.1
        - android-22
        - extra-android-m2repository
        - extra-android-support
    script:
        - ./gradlew assembleRelease
deploy:
    provider: releases
    api_key: afa7ab9fd5fdf2a3909938fcf069428d4b777ecb
    file: app/build/outputs/apk/app-release.apk
    skip_cleanup: true
    on:
        tags: true
